### ISSUE TITLE
Tooling yeoman generator

### ISSUE THREAD

**Issue by alber70g** [robinvanderknaap/SkaeleFrontend#1]
Maybe useful to use Yeoman generator-cg-angular. Very extensive set of tools and template generating for directives, tests, less, partials (controllers), etc., and uses great directory structure: https://github.com/cgross/generator-cg-angular

**Comment by robinvanderknaap** [comment]
Yes, I'm familiar with yeoman. Trying first how to get all parts to work together, before using yeoman. Maybe I will turn this template into a yeoman template later, when I understand everything :)

**Comment by robinvanderknaap** [comment]
Thnx for the tip btw
